exports.webhook = {
  business_type: 1,
  created_by: 12,
  order_id: 10537,
  job_id: 94749,
  job_type: 0,
  job_time: "2020-11-12T16:16:51.000Z",
  has_delivery: 1,
  has_pickup: 1,
  job_description: "",
  coupon_discount: 0,
  return_enabled: 0,
  job_pickup_phone: "+91424242444344",
  job_pickup_address:
    "Plot No. 5 Madhya Marg , Sector 28 B Chandigarh, 28B, Sector 28, Chandigarh, 160028, India",
  job_pickup_datetime: "11/12/2020 04:16 pm",
  checkout_template: [
    {
      label: "test1",
      value: "",
      data_type: "Date-Time",
      display_name: "asgjhasjfhjasf...asfh",
    },
    {
      cost: 0,
      label: "asdad6",
      value: "",
      option: [
        {
          cost: 2724,
          tags: ["asdasd", "asasf", "sfhajsf"],
          text: "asasddas",
          currency_id: 32,
        },
        {
          cost: 0,
          tags: [
            "dskhfsd",
            "skfhaksf",
            "asjfjasf",
            "ajsfaf",
            "jasfa",
            "sjgfgasf",
            "sfasf",
            "asfasf",
            "sdahksfk",
            "asfajsgfj",
            "asfgjasgf",
            "asgfjasf",
            "asasf",
            "aasfasf",
          ],
          text: "zczxc",
          currency_id: 32,
        },
      ],
      data_type: "Multi-Select",
      display_name: "asdad",
      allowed_values: ["asasddas", "zczxc"],
    },
    {
      cost: 0,
      label: "sdasfasf7",
      value: "",
      option: [
        {
          cost: 214124,
          tags: ["sdfsfaf", "asfasf"],
          text: "asfasfa",
          currency_id: 32,
        },
      ],
      data_type: "Single-Select",
      display_name: "sdasfasf",
      allowed_values: ["asfasfa"],
    },
    {
      label: "weruwersjfhjs*648742",
      value: "",
      data_type: "Date-Past",
      display_name: "weruwersjfhjs*64874asdasdaasdasd",
    },
    {
      label: "test_doc9",
      value: "",
      data_type: "Document",
      display_name: "test doc",
    },
    { label: "image8", value: "", data_type: "Image", display_name: "image" },
  ],
  job_delivery_datetime: "11/12/2020 05:16 pm",
  pickup_delivery_relationship: null,
  fleet_id: null,
  creation_datetime: "2020-11-12T10:46:50.000Z",
  vertical: 0,
  marketplace_user_id: 54125,
  created_at: "2020-11-12T10:46:50.000Z",
  form_id: 0,
  updated_at: "2020-11-17T07:23:11.000Z",
  transaction_id: "0",
  refunded_amount: null,
  remaining_balance: 0,
  tax: 35.25,
  delivery_charge: 15,
  total_amount: 90.25,
  order_amount: 35,
  payment_type: "ADYEN",
  surge_amount: 0,
  is_job_rated: 0,
  is_rating_deleted: 0,
  customer_rating: 0,
  customer_comment: "",
  pd_or_appointment: 1,
  user_id: 58551,
  timezone: "-300",
  merchant_email: "test233@yopmail.com",
  merchant_phone_number: "+919876567899",
  additional_charges: 0,
  additional_charge_label: null,
  overall_transaction_status: null,
  merchant_name: "testforAction",
  store_name_json: '{"en": "testforAction"}',
  merchant_is_deleted: 0,
  merchant_id: 58551,
  is_cancel_allowed: 1,
  tip: 5,
  delivery_method: 2,
  is_custom_order: 0,
  task_type: 0,
  is_urgent_delivery: 0,
  customer_id: 10537,
  customer_username: "Testgdhd",
  transaction_status: null,
  job_pickup_latitude: "30.7188978",
  job_pickup_longitude: "76.8102981",
  job_latitude: "30.7188978",
  job_longitude: "76.8102981",
  fugu_channel_id: "",
  is_pickup_anywhere: null,
  job_pickup_email: "test@yopmail.com",
  job_pickup_name: "Testgdhd",
  custom_pickup_address: "",
  custom_pickup_latitude: "0",
  custom_pickup_longitude: "0",
  merchant_module: 0,
  admin_setting_for_merchant: 1,
  delivery_by_merchant: null,
  job_status: 10,
  cancel_order_admin: 1,
  promo_code: null,
  customer_is_deleted: 0,
  is_cash_on_delivery: 0,
  enabled_payment_gateways: null,
  hold_amount: 0,
  tookan_scheduled_datetime: null,
  tookan_active_when_job_created: 0,
  merchant_earning: 12,
  commission_amount: 78.25,
  commission_payout_status: "UNPAID",
  customer_rating_by_merchant: 0,
  customer_review_by_merchant: "",
  order_preparation_time: 0,
  is_scheduled: 0,
  currency_code: "USD",
  currency_symbol: "$",
  merchant_enabled_payment_methods: null,
  merchant_payment_methods: 1,
  merchant_currency_id: null,
  transaction_charges: 0,
  debt_amount: 0,
  order_currency_symbol: "‎€",
  delivery_charge_surge_amount: 0,
  is_menu_enabled: 0,
  custom_pickup_name: null,
  custom_pickup_phone: null,
  custom_pickup_email: null,
  c_phone: "+91424242444344",
  j_address:
    "Plot No. 5 Madhya Marg , Sector 28 B Chandigarh, 28B, Sector 28, Chandigarh, 160028, India",
  c_email: "test@yopmail.com",
  c_username: "Testgdhd",
  city: "",
  customer_phone: "+91424242444344",
  job_address:
    "Plot No. 5 Madhya Marg , Sector 28 B Chandigarh, 28B, Sector 28, Chandigarh, 160028, India",
  customer_email: "test@yopmail.com",
  payment_method: 269,
  isEditAllowed: 1,
  payment_name: "adyen",
  show_refund_popup: 1,
  isEditedTask: 0,
  user_taxes: [
    {
      tax_name: "GST TEST",
      tax_percentage: 5,
      tax_amount: 1.75,
      tax_type: 0,
      delivery_tax: 0,
    },
    {
      tax_name: "GST TEST 2",
      tax_percentage: 10,
      tax_amount: 10,
      tax_type: 1,
      delivery_tax: 0,
    },
    {
      tax_name: "GST ON STORE",
      tax_percentage: 10,
      tax_amount: 3.5,
      tax_type: 0,
      delivery_tax: 0,
    },
    {
      tax_name: "GST ON STORE FIXED",
      tax_percentage: 20,
      tax_amount: 20,
      tax_type: 1,
      delivery_tax: 0,
    },
  ],
  edit_job_status: 0,
  show_status: 1,
  cancel_allowed: 1,
  updated_by: "Admin",
  reason: null,
  cancellation_reason: null,
  tookan_job_hash: null,
  agent_id: 0,
  amount_add_by_agent: null,
  pickup_barcode: null,
  delivery_barcode: null,
  job_otp: null,
  loyalty_points: {},
  fields: { custom_field: [] },
  is_customer_rated: 0,
  link_tasks: [],
  link_task: {},
  job_vertical: 0,
  acknowledged_datetime: "2020-11-17T07:23:12.522Z",
  barcode: "",
  arrived_datetime: "2020-11-17T07:23:12.522Z",
  completed_by_admin: 0,
  completed_datetime: "2020-11-17T07:23:12.522Z",
  customer_rating_by_driver: 0,
  distance_spent: 0,
  driver_comment: "",
  tookan_pickup_job_id: 0,
  tookan_delivery_job_id: 0,
  delivery_system_job_id: null,
  addon_id_for_order: null,
  team_id: 0,
  team_name: "",
  total_distance_travelled: 0,
  recurring_id: 0,
  region_id: 0,
  region_name: "",
  remarks: "",
  started_datetime: "2020-11-17T07:23:12.522Z",
  tags: "",
  task_history: [
    {
      creation_datetime: "2020-11-12T10:46:50.000Z",
      job_id: 0,
      fleet_id: 0,
      fleet_name: "",
      type: "",
      latitude: 0,
      longitude: 0,
      description: "",
    },
  ],
  total_order_amount: 0,
  promoList: [],
  transactionList: ["0"],
  job_status_text: "ORDERED",
  hippo_transaction_id: "94749_10537_58551",
  grouping_tags: ["GT_58551"],
  business_model_type: "HYPERLOCAL_PRODUCT",
};
